export enum Endpoints {
    ATHLETES = '/athletes',
    ATHLETES_LOGIN = '/athletes/login',
    ATHLETES_ME = '/athletes/me',
    ATHLETES_ME_PROFILEPIC = '/athletes/me/profilePic',
    ATHLETES_ID_PROFILEPIC = '/athletes/:id/profilePic',
    ATHLETES_LOGOUT = '/athletes/logout',
    ATHLETES_LOGOUTALL = '/athletes/logoutall',
    COACHES = '/coaches',
    COACHES_LOGIN = '/coaches/login',
    COACHES_ME = '/coaches/me',
    COACHES_LOGOUT = '/coaches/logout',
    COACHES_LOGOUTALL = '/coaches/logoutall',
    COACHES_ME_PROFILEPIC = '/coaches/me/profilePic',
    COACHES_ID_PROFILEPIC = '/coaches/:id/profilePic',
    SESSIONRPE = '/sessionRPE',
    SESSIONRPE_ID = '/sessionRPE/:id',
    POMS = '/poms',
    POMS_ID = '/poms/:id',
    ATHLETES_ME_CONNECTIONS = '/athletes/me/connections',
    ATHLETES_ME_CONNECTIONS_ID = '/athletes/me/connections/:id',
    ATHLETES_ME_CONNECTIONS_ACCEPT_ID = '/athletes/me/connections/accept/:id',
    ATHLETES_ME_CONNECTIONS_DECLINE_ID = '/athletes/me/connections/decline/:id',
    ATHLETES_ME_CONNECTIONS_REMOVE_ID = '/athletes/me/connections/remove/:id',
    COACHES_ME_CONNECTIONS = '/coaches/me/connections',
    COACHES_ME_CONNECTIONS_ID = '/coaches/me/connections/:id',
    COACHES_ME_CONNECTIONS_ACCEPT_ID = '/coaches/me/connections/accept/:id',
    COACHES_ME_CONNECTIONS_DECLINE_ID = '/coaches/me/connections/decline/:id',
    COACHES_ME_CONNECTIONS_REMOVE_ID = '/coaches/me/connections/remove/:id',
}

